### ISSUE TITLE
Suggested sitemap for website

### ISSUE THREAD

**Issue by peterdesmet** [enram/aloftdata.eu#18]
```yaml
- text: Explore data
  menu:
  - text: Biological data from European weather radars
  - text: Visualize
    href: https://crow.aloftdata.eu/
  - text: Browse
    href: /browse/
  - text: "---"
  - text: Radars
  - text: List of weather radars
    href: /radars/
  - text: "---"
  - text: File formats
  - text: VPTS CSV
    href: /vpts-csv/
  - text: ODIM bird profile
    href: https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification
- text: Discover more
  menu:
  - text: Datasets
    href: /datasets/
  - text: Software tools
    href: /software/
- text: FAQ
  href: /faq/
- text: About
  href: /about/
```
